### ISSUE TITLE
New feature: modules for integration plugins

### ISSUE THREAD

**Issue by herrvigg** [qtranslate/qtranslate-xt#661]
The provided **built-in modules** replace the legacy integration plugins:
- woo-commerce -> legacy plugin [WooCommerce & qTranslate-X](https://github.com/qTranslate-Team/woocommerce-qtranslate-x)
- gravity-forms -> legacy plugin [qTranslate support for GravityForms](https://github.com/wp-plugins/qtranslate-support-for-gravityforms)
- wp-seo -> legacy plugin [Integration: Yoast SEO & qTranslate-X](https://github.com/qTranslate-Team/wp-seo-qtranslate-x) (aka WP SEO)
- the other remaining [legacy plugins](https://github.com/qTranslate-Team) may follow soon.

Here is an example of the new options UI:

![image](https://user-images.githubusercontent.com/19155375/55479154-bc9da880-561d-11e9-962d-1863ac141ca3.png)

In short the new engine is generic:
* checks are first performed on the admin side, detecting the candidate modules from active plugins. Incompatible legacy plugins are detected and the admin is informed with a "_blocked_" status. The enabled modules are then stored in the new `qtranslate_modules` option.
* only the "_enabled_" modules are loaded, both on the client and/or admin side (this depends on the module hooks). The enabled list is retrieved from the `qtranslate_modules` option so the global overhead should be very limited. The disabled or blocked modules are **not** loaded!

This is now **merged in the master branch** so the developers are much welcome to test before official release. Note the code of the modules doesn't change yet compared to their plugin counterpart but these are the most recent versions - some were never released to WordPress! You can now make pull requests directly on the module code if you come up with bug fixes or new features.

The goal is to make the integration more convenient and the evolutions of the repo should be easier as a whole. In the future these built-in modules might be handled as separated projects again but this provides a better structure to move on.

This functionality may also be extended to handle new external custom modules as a new form of integration, not necessarily linked to other plugins.

**Comment by herrvigg** [comment]
Added a new module to replace the legacy plugin: [All in One SEO Pack & qTranslate-X](https://github.com/qTranslate-Team/all-in-one-seo-pack-qtranslate-x).
Seems to work fine for the admin settings but the fields for the posts are not translated, though the 
translatable fields are correctly set. At least we have something to start with.

More problematic, i noticed already some blocking JS errors with Yoast SEO. Will check later.

If some modules create problems and can't fix them we should just disable the concerned parts or the entire module in the worst case. But the goal is that most people (developers and testers) go through most of it so we can better evaluate this. Some bugs might be in common so the whole repo will benefit from it.

**Comment by herrvigg** [comment]
I had to disable the module Yoast SEO, it's obsolete and needs too much work with the JS part :(
In general the JS code is the most problematic because this old-school integration is just an awful hack assuming some global variables are found. It's a complete nightmare to maintain, i've rarely seen something hacky like this... If you only take the JS part there's not so much code but it needs to be completely refactored with modern coding and i won't have time for that.

I only commented the definition of the module and a small piece of code that has no chance to work, but i left the module in case some people wants to look at it. To do so, just uncomment the definition in `modules/qtx_modules_handler.php` and try it out. Maybe the PHP code can be useful, if someone manage to make it work even partially let me know .

**Comment by herrvigg** [comment]
It would be really good to have something with Yoast SEO though. As said even if it's partial, it's always better than nothing. The hardest part is the JS side, but maybe something better can be done simply in PHP. Help is welcome!

Looking more forward there is a strong need to integrate modern JS frameworks such as npm and bundlers like webpack. The old-fashion JS interface is not viable anymore. The refactoring of the integration should start from this imo.

**Comment by herrvigg** [comment]
Added new modules:
- ACF: converted from [ACF qTranslate](https://github.com/funkjedi/acf-qtranslate). This plugin is actively maintained thanks to @funkjedi who did an awesome job! The code is very clean and this could help to define new templates and structure for better integrations. Note ACF Pro is not handled yet as module, our new module handler requires a few changes to deal with this case (two plugins pointing to the same module).
- Events Made Easy: converted from [Events Made Easy & qTranslate-X](https://wordpress.org/plugins/events-made-easy-qtranslate-x/). Note the version at WordPress.org was more recent than its github project so that's also a good sign of healthy state. It would great to have @liedekef involved!

Disclaimer: these modules should be considered as *work in progress* before proceeding with the transition of qTranslate-XT. We don't claim ownership of these components and we'll figure how to involve the contributors properly.

**Comment by herrvigg** [comment]
Added support for ACF PRO.

I removed the remaining integration notices that became obsolete. All this part with the old integration plugins is now gone!

[WPBakery Visual Composer & qTranslate-X](https://github.com/qTranslate-Team/js-composer-qtranslate-x): not updated for 4 years. Though there were many files in the project the plugin was doing almost nothing. I looks just like a draft project.

[Fusion Core & qTranslate-X](https://github.com/qTranslate-Team/fusion-core-qtranslate-x): not updated for 3 years. From what i understand Fusion Core is not a popular plugin as a standalone but rather through [Theme Fusion](https://theme-fusion.com/wordpress-5-0-avada-and-you-all-that-you-need-to-know/), with Avada and Fusion Builder. However as mentioned by @scrobbleme the integration plugin is not working since Avada 5 (see issue https://github.com/qTranslate-Team/fusion-core-qtranslate-x/issues/1). It would be good if this could be revived! This plugin was not doing much so if the Fusion part didn't change that much it should be feasible.

**Comment by herrvigg** [comment]
The handler for the modules is currently too simplistic as it rechecks all everytime. It should be more event-driven, updating only on the main plugin activation (qTranslate-XT) and later when every related plugin is activated/deactivated. A good reason for this is about admin permissions, the modules states should only be altered by someone having full admin rights. So this should be better integrated in qTranslate sequence of events but it doesn't prevent to test the components already now.

**Comment by liedekef** [comment]
> Added new modules:
> 
> * ACF: converted from [ACF qTranslate](https://github.com/funkjedi/acf-qtranslate). This plugin is actively maintained thanks to @funkjedi who did an awesome job! The code is very clean and this could help to define new templates and structure for better integrations. Note ACF Pro is not handled yet as module, our new module handler requires a few changes to deal with this case (two plugins pointing to the same module).
> * Events Made Easy: converted from [Events Made Easy & qTranslate-X](https://wordpress.org/plugins/events-made-easy-qtranslate-x/). Note the version at WordPress.org was more recent than its github project so that's also a good sign of healthy state. It would be great to have @liedekef involved!
> 
> Disclaimer: these modules should be considered as _work in progress_ before proceeding with the transition of qTranslate-XT. We don't claim ownership of these components and we'll figure out how to involve the contributors properly.

I'll try to take a look at this (concerning Events Made Easy). Any documentation or so?
Franky

**Comment by herrvigg** [comment]
> I'll try to take a look at this (concerning Events Made Easy). Any documentation or so?

Awesome! For the documentation, the most important should be in the README.md, see section FAQ. For the modules, it's just a wrapper around the old plugins, so the code of those is not changed yet. The first goal is just to see if there are no regressions. Next step fix the existing bugs (starting with the most annoying).

The evolution of qTranslate-XT can then be done in parallel, now that the code of the main support plugins is in a single repo it should be way easier to manage. Later on the modules could return back to separate git projects, but imo it's overkill (and a bad idea) to have them as WP plugins. This integration should only be internal to qTranslate with a better structure.

**Comment by paketos** [comment]
Can you please add support for "Custom Product Tabs for WooCommerce" ? I tried qTranslate-X and I was able to see flags to choose in all custom tabs added to products. After disabling the plugin and installing the new plugin i cannot see anymore flags in the custom tabs.
Furthermore i would like to highlight that after disabling "WPBakery Visual Composer & qTranslate-X" I can still see flags in pages built with WPBakery. Do you natively support this page builder without the need for a module? 
Last comment is the qtranslate-slug gives me a lot of issues, like product pages lead to posts therefore I disabled it but i am not able to translate slugs anymore. Any thoughts to make this as a standard option for the new plugin?
I hope you carry on with your work and make this plugin my standard choice for all my future projects.
Thanx

**Comment by herrvigg** [comment]
> Can you please add support for "Custom Product Tabs for WooCommerce" ? I tried qTranslate-X and I was able to see flags to choose in all custom tabs added to products.

Which versions were you using? For qTranslate-X and for the support plugin?

> After disabling the plugin and installing the new plugin i cannot see anymore flags in the custom tabs.

New plugin = qTranslate-XT? Which version?

> Furthermore i would like to highlight that after disabling "WPBakery Visual Composer & qTranslate-X" I can still see flags in pages built with WPBakery. Do you natively support this page builder without the need for a module?
Depending on the pages and the fields yes there might be some flags. Was this support plugin working? It didn't seem to do anything relevant but if it does we can check this again.

> Last comment is the qtranslate-slug gives me a lot of issues, like product pages lead to posts therefore I disabled it but i am not able to translate slugs anymore. Any thoughts to make this as a standard option for the new plugin?

As discussed in https://github.com/qtranslate/qtranslate-xt/issues/660 it's not something i will deal with right now, there are too many other tasks to do and this is just on my free time. There seems to be a bunch of bugs reported both at Wordpress.org and on github but for @bagaweb it worked well. I hope something can be integrated some day, or at least supported by a plugin and maintained.

**Comment by herrvigg** [comment]
I have now pushed new changes to handle dynamically the activation/deactivation of related plugins through new hooks. It was not easy because WP Core is badly designed with the deactivations (i may send them an issue later). Anyway i found a way to handle this, it should work fine now. The new solution with the module status is a bit more complicated but it should now cover the cases when someone doesn't have the admin rights to change the plugins state.

There might be some inconsistencies with the past values so the best is to deactivate/reactivate qTranslate-XT to get everything updated properly. In fact this is a general rule when installing a version manually, you should always go through the main activation hook.

If you ever have some problems with the modules you can simply delete the option `qtranslate_modules` and this part will be reset.

**Comment by herrvigg** [comment]
I've slightly changed the module status for better consistency with the code. It now becomes _active/inactive_ to follow the state plugin in the general case. 

![image](https://user-images.githubusercontent.com/19155375/56326800-d1c71b00-6177-11e9-8e0f-864c1aca6a0e.png)

Also, i feel that _enabled/disabled_ was more corresponding to a user/admin setting, that could be a future feature. We can see the current activation as semi-automatic (from the plugin activation). But i have the intuition it could be extended. If the modules could deal with more integration beyond the built-in ones we could imagine giving more control. I think it can be a good way for a supervision of other custom modules externally defined. Currently it's such a hassle trying to understand which i18 config files are loaded... eventually we should also should try to get rid of those.

**Comment by The3IC** [comment]
OK, I tried the version from the repository today. Observations:
- I have WC 3.6.1, All in 1 SEO Pro 2.5.4.1 and JS Composer (WP Bakery Page Builder) 5.7
- WC was correctly identified and worked mostly, there is one issue remaining and that is that Product Structured Data element "Product Name" and "Description" are not translated (the [..] .. format is shown in the code and hence will be picked up by Google into search results). I have fixed this by editing one of the WC files and added __() on lines 202 and 205 in the file class-wc-structured-data.php. I have reported this issue to WC but in their typical arrogant fashion :-) have ignored it, perhaps a real developer could get them to add the translation to the structured data generation.
- JS composer was not identified but seems to work without any problems
- All in One SEO Pro was NOT identified and hence the SEO fields missbehaved showing the [..] format when editing a page.

**Comment by herrvigg** [comment]
Cool, thanks!

- WooCommerce: sounds good! For the change you propose, i can somehow understand they don't want to add extra calls they consider too specific. Functions like `__()` are meant to be use for static text only but here it's about user product so my first feeling is that it should be done differently. From a qTranslate perspective it should be stored in multi-lang and converted for the current lang only before display. I can't tell yet how to do that in practice for this case but with WP plugins the solution for tricky cases is rather to ask for a new action/filter. But it has to be done at the right place.
- JS composer / WP Bakery: cool if it works out of the box! The old [support plugin](https://github.com/qTranslate-Team/js-composer-qtranslate-x) doesn't seem to do anything so i didn't include it.
- All in One SEO Pro: the support for Pro should be straightforward. You can try this, see line 53 in qtx_modules_handler (link given below):
`'plugin'       => 'all-in-one-seo-pack/all_in_one_seo_pack.php'`
Change it with:
`'plugin'       => array('all-in-one-seo-pack/all_in_one_seo_pack.php', '<plugin name PRO>')`

https://github.com/qtranslate/qtranslate-xt/blob/e181cefb1e1b35c53fceea533a13f2dd3dc9d6f8/modules/qtx_modules_handler.php#L53

See the format for the free version and replace with the good value. This will only activate the module. If there are very specific features with the Pro compared to the free also impacting qTranslate they have to be implemented in the module.

I made a quick test with the Free version, it's working kind of okay i'd say, some fields are handled but the UX is quite bad because it's counting characters beyond a single language. The page description is not translated for display but it's hard to reach that part with the current qTranslate tools (substring in a HTML node text).

In general it's not easy to deal with SEO data in qTranslate as they are many factors with respect to the URLs, canonical URLs and all this stuff.

**Comment by herrvigg** [comment]
For WooCommerce: i just noticed a few lines below there is this filter `('woocommerce_structured_data_product', $markup, $product)`. The whole product object is sent so maybe this is the solution if you can change the fields of interest in that object.

For All in One SEO Pro, after you have changed the string to array you just have to reactivate qTranslate so it can update the active modules.

**Comment by The3IC** [comment]
I'll test the AllIn1 later, as for the ('woocommerce_structured_data_product', $markup, $product), I have no idea how to set up such a filter. Perhaps the filter can be integrated into XT or alternatively there would be some code that can be copied to functions-php by the likes of my with limited coding skills. The changes as I said are very simple and limited, only the product name and description need to be translated.

**Comment by herrvigg** [comment]
Try something like this:
```
add_filter( 'woocommerce_structured_data_product', 'filter_woocommerce_structured_data_product', 10, 2 );

function filter_woocommerce_structured_data_product( $markup, $product ) {
  $markup['name'] = <your stuff>; 
  $markup['description'] = <your stuff>;
  return $markup;
}
```
Just add it in your functions.php for now. Maybe this can solve other i18n issues for WC with qTranslate but in general when done at a low level you always need 2 transformations, one for reading one language from the DB and one for writing all languages in the DB.

Did you try with All in One SEO Pro? Can you give me the full plugin name? For the free version it's `all-in-one-seo-pack/all_in_one_seo_pack.php`. The Pro plugin should be added by default in the modules.

**Comment by The3IC** [comment]
Did I get it right? Still shows as "Inactive" in the list?
`			array(
				'id'           => 'all-in-one-seo-pack',
				'name'         => 'All in One SEO Pack',
				'plugin' => array('all-in-one-seo-pack/all_in_one_seo_pack.php', 'all-in-one-seo-pack-pro/all_in_one_seo_pack.php'),
				'incompatible' => 'all-in-one-seo-pack-qtranslate-x/qaioseop.php'
			),`

Also for the functions.php, the below code gets the correct language version but for the description I still get the markup included. How would I get rigd of the markup? Ideally I would also like to first test if the excerpt it set and use that, any idea how to code that?

`add_filter( 'woocommerce_structured_data_product', 'filter_woocommerce_structured_data_product', 10, 2 );

function filter_woocommerce_structured_data_product( $markup, $product ) {
  $markup['name'] = __($product->get_name()); 
  $markup['description'] = __($product->get_short_description());
  return $markup;
}`

**Comment by herrvigg** [comment]
All in One SEO Pro: did you disactivate/reactive qTranslate-XT?

WC filter: i don't think the `__(xxx)` call is a viable long-term solution but it can be a temporary workaround. If you check the original code see this:
```
'description' => wp_strip_all_tags( do_shortcode( $product->get_short_description() ? $product->get_short_description() : $product->get_description() ) ),
```
I don't know how the content looks like but the logic would rather be this: `$markup['description'] = __($markup['description']);`
Otherwise you will undo some of the changes done earlier. Same should apply to the name field.

**Comment by The3IC** [comment]
AllIn1: 
- Plugin reactivation did the job
- The basic setup (SEO title and description) work, for instance the Social Media not. 
- I have been using the plugin "Open Graph for Facebook, Google+ and Twitter Card Tags" for social and it works nicely nowadays (I used to do a __() on that one as well :-) ) so perhaps you could pick up this module for -XT support? There are just a couple of text fields, one in the settings and one on each page.

Structured data.
- Cool, now it works nicely. Can you somehow roll this into the Woocommerce module?
- What would be a long term solution then? Is it using apply_filters('translate_text', .....)?

**Comment by herrvigg** [comment]
- Missing social media: now that the module is in place anyone can send PR for the fixes. These bugs were existing already before and I won't work on these specific parts.
- Open Graph for FB, G+ and twitter: i don't know what this is about, it's a new topic. I won't work on this but you or anyone else is welcome to send PR for new features.
- WC: i won't push that change, it was only to help you as a workaround but it's too specific. I don't know what the best solution is, but as said __() is for static text, not items that can change such as product name. This is about PHP development and i won't enter more into the details.

**Comment by herrvigg** [comment]
The modules are now officially released with 3.6.0! Farewell old plugins, they are now past history! I close this topic. Everyone is welcome to send PR for new fixes.

**Comment by herrvigg** [comment]
In general we will have a billion problems of integration. Having a bunch of plugins was a nightmare so i'm convinced the module approach is the good one! Now the other risk is that all these specific problems accumulate and clutter the issues about the core functionalities. So maybe all modules should live in a separate github project at some point, or at least the bigger ones as WC and ACF. But most importantly we should try to define a proper API.

**Comment by kochhase** [comment]
Hi there i have an problem with the gravity form multiupload option insite gravity. WPML has there as well some problems in the past. So this is the Problem that WPML had to fixed. Mybe that helps for an solution for qtranslate-x.
Pass session arguments between domains through the language switcher" - we had this (must have been by default) as Pass arguments via GET (the url). We changed that to Pass arguments via POST, and it seems to have resolved the issue with the Gravity Forms multi-file upload button ghosting out.
is there an easy fix for that problem?

**Comment by kochhase** [comment]
Hi there another problem. no way to use conditional Logic. Ore is this the same problem like before?
thanks for looking. I can send you the gravity form plugin if needed.

**Comment by alikkis** [comment]
JS composer / WP Bakery & qTranslate-X : cool if it works out of the box! But after updating to WP Bakery 6.5.0 - stopped working on my site
