### ISSUE TITLE
[ACF] wysiwyg fields which are created with acf-qtranslate overwrite the translation

### ISSUE THREAD

**Issue by Vegys** [qtranslate/qtranslate-xt#879]
Hi, I have a problem, wysiwyg fields which are created with acf-qtranslate overwrite the translation.

The problem appeared when the acf pro plugin was updated to version 5.9.0. In version 5.8.9 I did not notice any problems.

Is there a solution?

WP version 5.5.1

Thank!

**Comment by francescocortese** [comment]
I have same problem. how to fix it?

**Comment by antonzol** [comment]
same problem
translation does not loaded in wysiwyg (only one language) and it owerwrite others

**Comment by francescocortese** [comment]
The problem is inside the module ACF qTranslate. I update also qtranslatext to last version, this bug still exist.

**Comment by francescocortese** [comment]
I'm trying to find a solution, but nothing. Any news? @herrvigg

**Comment by natzar** [comment]
+1

**Comment by alexandrerauscher** [comment]
+1 here, french / english translations with ACF wysiwyg content editor are overriding each other, any fix?
Got this JS error on the console (maybe related, maybe not):
`qtranslatex.min.js?ver=3.9.0:1 Uncaught TypeError: Cannot read property 'prototype' of undefined` in qtranslatex.min.js

**Comment by natzar** [comment]
I fixed this.

- Be sure your ACF field is Qtranslate Textarea.
- Also this: https://www.zighead.com/2016/08/advanced-custom-fields-qtranslate-x/

**Comment by francescocortese** [comment]
> I fixed this.
> 
> * Be sure your ACF field is Qtranslate type [Textarea], not jus textarea.
> * Also this: https://www.zighead.com/2016/08/advanced-custom-fields-qtranslate-x/

Doesn't work with wysiwyg fields.

**Comment by natzar** [comment]
> > I fixed this.
> > 
> > * Be sure your ACF field is Qtranslate type [Textarea], not jus textarea.
> > * Also this: https://www.zighead.com/2016/08/advanced-custom-fields-qtranslate-x/
> 
> Doesn't work with wysiwyg fields.

What you mean doesn't work?

**Comment by francescocortese** [comment]
> > > I fixed this.
> > > 
> > > * Be sure your ACF field is Qtranslate type [Textarea], not jus textarea.
> > > * Also this: https://www.zighead.com/2016/08/advanced-custom-fields-qtranslate-x/
> > 
> > 
> > Doesn't work with wysiwyg fields.
> 
> What you mean doesn't work?

This doesn't fix the wysiwyg fields bug when change language. Still overwrite the translation.

**Comment by natzar** [comment]
- On ACF fields, do you have "Qtranslate WYSIWYG" as field type?
- Follow those instructions to add .translatable class
- Maybe delete anything on post_meta for the post.

It works for me. WordPress + ACF last version + qtranslatext + qtranslate_acf module

**Comment by francescocortese** [comment]
> * On ACF fields, do you have "Qtranslate WYSIWYG" as field type?
> * Follow those instructions to add .translatable class
> * Maybe delete anything on post_meta for the post.
> 
> It works for me. WordPress + ACF last version + qtranslatext + qtranslate_acf module

Doesn't, maybe because I use ACF Pro 5.9.1?

**Comment by alexandrerauscher** [comment]
I think on this thread we are all using "classic" wysiwyg acf field (and not the Qtranslate wysiwyg one, that is on bottom of the list of field types). I will try to migrate the field type for existing content and see if there is any side effect!

**Comment by francescocortese** [comment]
> I think on this thread we are all using "classic" wysiwyg acf field (and not the Qtranslate wysiwyg one, that is on bottom of the list of field types). I will try to migrate the field type for existing content and see if there is any side effect!

Oh, yes! Now it work... Thanks so much!!!

**Comment by natzar** [comment]
@francescocortese  it's what I've said on my first message without the word classic : |

**Comment by francescocortese** [comment]
> @francescocortese it's what I've said on my first message without the word classic : |

Don't worry, thanks for supporting me anyway. ✨

**Comment by Vegys** [comment]
The problem was indeed that the field was created without qtranslate, changed the field type and the problem went away ...
amazing that it worked before =))
